:current-version: 1.0.0-SNAPSHOT

= Image Metadata processing using Java

This repository contains examples for processing image metadata using Java. Currently, the following module
is available:

*image-metadata-commons-imaging*

This https://spring.io/projects/spring-boot[Spring Boot] 3 application will allow you to upload images (JPG, PNG, GIF) and the application will extract the
metadata from the files. This includes:

- *EXIF* (Exchangeable image file format)
- *IPTC* (International Press Telecommunications Council)
- *XMP* (eXtensible Metadata Platform)
- Generic *file* metadata

== Building from Source

=== Requirements

- https://www.oracle.com/java/technologies/javase/jdk17-archive-downloads.html[Java 17]
- https://help.github.com/set-up-git-redirect[Git]
- For native compilation: https://www.graalvm.org/downloads/[GraalVM 22.3.1]

=== Check out source code

Check out the project using https://git-scm.com/[Git]:

[source,bash,indent=0]
----
git clone https://github.com/ghillert/image-metadata.git
cd image-metadata
----

=== Build

```bash
./mvnw clean package
```

=== Run

```bash
java -jar ./image-metadata-commons-imaging/image-metadata-commons-imaging-{current-version}.jar
```

=== Run + Run in one go

```bash
./mvnw spring:run
```

== Going Native

=== Local Native Image

Creating a local image should be as easy as:

```bash
./mvnw clean package -DnativeCompile
```

This shorthand system property will activate the Maven profiles:

- native
- nativeCompile

```bash
./mvnw clean package -Pnative,nativeCompile
```

==== macOS

As the application uses some AWT classes for image processing, the native
version for macOS will not run. There is an
https://github.com/oracle/graal/issues/4124[open GitHub issue] at the GraalVM
project.

If you try, you will see an exception like the following:

```
2023-02-12T09:38:34.721-10:00 ERROR 65901 --- [nio-8080-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed: java.lang.UnsatisfiedLinkError: no awt in java.library.path] with root cause

java.lang.UnsatisfiedLinkError: no awt in java.library.path
...
```

==== Windows

On Windows it is critical to compile the project using the
*x64 Native Tools Command Prompt for VS 2022*. See the following blog posts
for more information:

- https://medium.com/graalvm/using-graalvm-and-native-image-on-windows-10-9954dc071311

Loading the font sub-system reqires you to specify the Java Home directory:

```
image-metadata-commons-imaging.exe -Djava.home="%JAVA_HOME%"
```

While this will work, you can reduce the contents of `java.home` to just one file `fontconfig.properties` with the contents:

```properties
version=1
sequence.allfonts=default
```

For more information see:

- https://github.com/adoptium/temurin-build/issues/693

For completeness, the following resource shall be mentioned as well, but it turns out, not all mentioned files are needed:

- https://www.jianshu.com/p/a53ae350f845?v=1669292961020

==== Linux

Not tested, yet, but should just work :-) See the instructions for Docker below.

https://github.com/graalvm/mandrel/issues/189
apt install gcc zlib1g-dev build-essential libfreetype6-dev

=== Docker

_image-metadata-commons-imaging_ uses fonts, which on Linux require `fontconfig`
to be installed. That's why I use `paketobuildpacks/builder:full` and not the
default `paketobuildpacks/builder:tiny`.

IMPORTANT: Please make sure your Docker daemon is running.

```bash
./mvnw -Pnative spring-boot:build-image -pl :image-metadata-commons-imaging
docker run --rm -p 8080:8080 docker.io/library/image-metadata-commons-imaging:{current-version}
```

```bash
./mvnw clean package -Pnative
```

== Development

When adding functionality, it may be necessary to run the *native-image-agent*:

```bash
java -Dspring.aot.enabled=true -agentlib:native-image-agent=config-output-dir=./out/ -jar target/image-metadata-commons-imaging-{current-version}.jar
```

== License

Image Metadata is licensed under the link:LICENSE[Apache License] (ASL), Version 2.0.
=======
= Image Metadata processing using Java

Examples for processing image metadata using Java

== Requirements

- Java 17
- For native compilation: 22.3.r19-grl

== Build

```bash
./mvn clean package
```

=== Native Image (local OS)

```bash
./mvnw clean package -Pnative
```

Windows

x64 Native Tools Command Prompt for VS 2022
/c/Users/hille/.sdkman/candidates/java/current/bin/java


Resources

https://www.jianshu.com/p/a53ae350f845?v=1669292961020


Run Agent

